#ifndef LANGUAGE_H
#define LANGUAGE_H

// NOTE: IF YOU CHANGE THIS FILE / MERGE THIS FILE WITH CHANGES
//
//   ==> ALWAYS TRY TO COMPILE MARLIN WITH/WITHOUT "ULTIPANEL" / "ULTRALCD" / "SDSUPPORT" #define IN "Configuration.h" 
//   ==> ALSO TRY ALL AVAILABLE "LANGUAGE_CHOICE" OPTIONS

// Languages
// 1  English
// 2  Polish
// 3  French	(awaiting translation!)
// 4  German
// 5  Spanish
// 6  Russian
// 7  Italian
// 8  Portuguese

#define LANGUAGE_CHOICE 1  // Pick your language from the list above

#define PROTOCOL_VERSION "1.0"

#if MOTHERBOARD == 7 || MOTHERBOARD == 71
	#define MACHINE_NAME "Ultimaker"
	#define FIRMWARE_URL "http://firmware.ultimaker.com"
#else
	#define MACHINE_NAME "Mendel"
	#define FIRMWARE_URL "http://www.mendel-parts.com"
#endif

#define STRINGIFY_(n) #n
#define STRINGIFY(n) STRINGIFY_(n)

#if LANGUAGE_CHOICE == 1

// LCD Menu Messages
	#define WELCOME_MSG MACHINE_NAME " Ready."
	#define MSG_SD_INSERTED "Card inserted"
	#define MSG_SD_REMOVED "Card removed"
	#define MSG_MAIN " Main \003"
	#define MSG_AUTOSTART " Autostart"
	#define MSG_DISABLE_STEPPERS " Disable Steppers"
	#define MSG_AUTO_HOME " Auto Home"
	#define MSG_SET_ORIGIN " Set Origin"
	#define MSG_PREHEAT_PLA " Preheat PLA"
	#define MSG_PREHEAT_PLA_SETTINGS " Preheat PLA Setting"
	#define MSG_PREHEAT_ABS " Preheat ABS"
	#define MSG_PREHEAT_ABS_SETTINGS " Preheat ABS Setting"
	#define MSG_COOLDOWN " Cooldown"
	#define MSG_EXTRUDE " Extrude"
	#define MSG_RETRACT " Retract"
	#define MSG_PREHEAT_PLA " Preheat PLA"
	#define MSG_PREHEAT_ABS " Preheat ABS"
	#define MSG_MOVE_AXIS " Move Axis      \x7E"
	#define MSG_SPEED " Speed:"
	#define MSG_NOZZLE " \002Nozzle:"
	#define MSG_NOZZLE1 " \002Nozzle2:"
	#define MSG_NOZZLE2 " \002Nozzle3:"
	#define MSG_BED " \002Bed:"
	#define MSG_FAN_SPEED " Fan speed:"
	#define MSG_FLOW " Flow:"
	#define MSG_CONTROL " Control \003"
	#define MSG_MIN " \002 Min:"
	#define MSG_MAX " \002 Max:"
	#define MSG_FACTOR " \002 Fact:"
	#define MSG_AUTOTEMP " Autotemp:"
	#define MSG_ON "On "
	#define MSG_OFF "Off"
	#define MSG_PID_P " PID-P: "
	#define MSG_PID_I " PID-I: "
	#define MSG_PID_D " PID-D: "
	#define MSG_PID_C " PID-C: "
	#define MSG_ACC  " Acc:"
	#define MSG_VXY_JERK " Vxy-jerk: "
	#define MSG_VMAX " Vmax "
	#define MSG_X "x:"
	#define MSG_Y "y:"
	#define MSG_Z "z:"
	#define MSG_E "e:"
	#define MSG_VMIN " Vmin:"
	#define MSG_VTRAV_MIN " VTrav min:"
	#define MSG_AMAX " Amax "
	#define MSG_A_RETRACT " A-retract:"
	#define MSG_XSTEPS " Xsteps/mm:"
	#define MSG_YSTEPS " Ysteps/mm:"
	#define MSG_ZSTEPS " Zsteps/mm:"
	#define MSG_ESTEPS " Esteps/mm:"
	#define MSG_MAIN_WIDE " Main        \003"
	#define MSG_RECTRACT_WIDE " Rectract    \x7E"
	#define MSG_TEMPERATURE_WIDE " Temperature \x7E"
	#define MSG_TEMPERATURE_RTN " Temperature  \003"
	#define MSG_MOTION_WIDE " Motion      \x7E"
	#define MSG_STORE_EPROM " Store memory"
	#define MSG_LOAD_EPROM " Load memory"
	#define MSG_RESTORE_FAILSAFE " Restore Failsafe"
	#define MSG_REFRESH "\004Refresh"
	#define MSG_WATCH " Watch   \003"
	#define MSG_PREPARE " Prepare \x7E"
	#define MSG_PREPARE_ALT " Prepare \003"
	#define MSG_CONTROL_ARROW " Control \x7E"
	#define MSG_RETRACT_ARROW " Retract \x7E"
	#define MSG_TUNE " Tune    \x7E"
	#define MSG_PAUSE_PRINT " Pause Print \x7E"
	#define MSG_RESUME_PRINT " Resume Print \x7E"
	#define MSG_STOP_PRINT " Stop Print   \x7E"
	#define MSG_CARD_MENU " Card Menu    \x7E"
	#define MSG_NO_CARD " No Card"
	#define MSG_DWELL "Sleep..."
	#define MSG_USERWAIT "Wait for user..."
	#define MSG_NO_MOVE "No move."
	#define MSG_PART_RELEASE "Partial Release"
	#define MSG_KILLED "KILLED. "
	#define MSG_STOPPED "STOPPED. "
	#define MSG_STEPPER_RELEASED "Released."
	#define MSG_CONTROL_RETRACT  " Retract mm:"
	#define MSG_CONTROL_RETRACTF " Retract  F:"
	#define MSG_CONTROL_RETRACT_ZLIFT " Hop mm:"
	#define MSG_CONTROL_RETRACT_RECOVER " UnRet +mm:"
	#define MSG_CONTROL_RETRACT_RECOVERF " UnRet  F:"
	#define MSG_AUTORETRACT " AutoRetr.:"
        #define MSG_SERIAL_ERROR_MENU_STRUCTURE "Something is wrong in the MenuStructure."

// Serial Console Messages

	#define MSG_Enqueing "enqueing \""
	#define MSG_POWERUP "PowerUp"
	#define MSG_EXTERNAL_RESET " External Reset"
	#define MSG_BROWNOUT_RESET " Brown out Reset"
	#define MSG_WATCHDOG_RESET " Watchdog Reset"
	#define MSG_SOFTWARE_RESET " Software Reset"
	#define MSG_MARLIN "Marlin "
	#define MSG_AUTHOR " | Author: "
	#define MSG_CONFIGURATION_VER " Last Updated: "
	#define MSG_FREE_MEMORY " Free Memory: "
	#define MSG_PLANNER_BUFFER_BYTES "  PlannerBufferBytes: "
	#define MSG_OK "ok"
	#define MSG_FILE_SAVED "Done saving file."
	#define MSG_ERR_LINE_NO "Line Number is not Last Line Number+1, Last Line: "
	#define MSG_ERR_CHECKSUM_MISMATCH "checksum mismatch, Last Line: "
	#define MSG_ERR_NO_CHECKSUM "No Checksum with line number, Last Line: "
	#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "No Line Number with checksum, Last Line: "
	#define MSG_FILE_PRINTED "Done printing file"
	#define MSG_BEGIN_FILE_LIST "Begin file list"
	#define MSG_END_FILE_LIST "End file list"
	#define MSG_M104_INVALID_EXTRUDER "M104 Invalid extruder "
	#define MSG_M105_INVALID_EXTRUDER "M105 Invalid extruder "
	#define MSG_ERR_NO_THERMISTORS "No thermistors - no temperature"
	#define MSG_M109_INVALID_EXTRUDER "M109 Invalid extruder "
	#define MSG_HEATING "Heating..."
	#define MSG_HEATING_COMPLETE "Heating done."
	#define MSG_BED_HEATING "Bed Heating."
	#define MSG_BED_DONE "Bed done."
	#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
	#define MSG_COUNT_X " Count X: "
	#define MSG_ERR_KILLED "Printer halted. kill() called!"
	#define MSG_ERR_STOPPED "Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"
	#define MSG_RESEND "Resend: "
	#define MSG_UNKNOWN_COMMAND "Unknown command: \""
	#define MSG_ACTIVE_EXTRUDER "Active Extruder: "
	#define MSG_INVALID_EXTRUDER "Invalid extruder"
	#define MSG_X_MIN "x_min: "
	#define MSG_X_MAX "x_max: "
	#define MSG_Y_MIN "y_min: "
	#define MSG_Y_MAX "y_max: "
	#define MSG_Z_MIN "z_min: "
	#define MSG_Z_MAX "z_max: "
	#define MSG_M119_REPORT "Reporting endstop status"
	#define MSG_ENDSTOP_HIT "TRIGGERED"
	#define MSG_ENDSTOP_OPEN "open"

	#define MSG_SD_CANT_OPEN_SUBDIR "Cannot open subdir"
	#define MSG_SD_INIT_FAIL "SD init fail"
	#define MSG_SD_VOL_INIT_FAIL "volume.init failed"
	#define MSG_SD_OPENROOT_FAIL "openRoot failed"
	#define MSG_SD_CARD_OK "SD card ok"
	#define MSG_SD_WORKDIR_FAIL "workDir open failed"
	#define MSG_SD_OPEN_FILE_FAIL "open failed, File: "
	#define MSG_SD_FILE_OPENED "File opened: "
	#define MSG_SD_SIZE " Size: "
	#define MSG_SD_FILE_SELECTED "File selected"
	#define MSG_SD_WRITE_TO_FILE "Writing to file: "
	#define MSG_SD_PRINTING_BYTE "SD printing byte "
	#define MSG_SD_NOT_PRINTING "Not SD printing"
	#define MSG_SD_ERR_WRITE_TO_FILE "error writing to file"
	#define MSG_SD_CANT_ENTER_SUBDIR "Cannot enter subdir: "

	#define MSG_STEPPER_TO_HIGH "Steprate to high: "
	#define MSG_ENDSTOPS_HIT "endstops hit: "
	#define MSG_ERR_COLD_EXTRUDE_STOP " cold extrusion prevented"
	#define MSG_ERR_LONG_EXTRUDE_STOP " too long extrusion prevented"

#endif


#if LANGUAGE_CHOICE == 2

// LCD Menu Messages
	#define WELCOME_MSG MACHINE_NAME " Gotowe."
	#define MSG_SD_INSERTED "Karta wlozona"
	#define MSG_SD_REMOVED "Karta usunieta"
	#define MSG_MAIN " Menu \003"
	#define MSG_AUTOSTART " Autostart"
	#define MSG_DISABLE_STEPPERS " Wylacz silniki"
	#define MSG_AUTO_HOME " Auto. poz. zerowa"
	#define MSG_SET_ORIGIN " Ustaw punkt zerowy"
	#define MSG_PREHEAT_PLA " Rozgrzej PLA"
	#define MSG_PREHEAT_PLA_SETTINGS " Ustawienia roz. PLA"
	#define MSG_PREHEAT_ABS " Rozgrzej ABS"
	#define MSG_PREHEAT_ABS_SETTINGS " Ustawienia roz. ABS"
	#define MSG_COOLDOWN " Chlodzenie"
	#define MSG_EXTRUDE " Ekstruzja"
	#define MSG_RETRACT " Cofanie"
	#define MSG_MOVE_AXIS " Ruch osi       \x7E"
	#define MSG_SPEED " Predkosc:"
	#define MSG_NOZZLE " \002Dysza:"
	#define MSG_NOZZLE1 " \002Dysza2:"
	#define MSG_NOZZLE2 " \002Dysza3:"
	#define MSG_BED " \002Loze:"
	#define MSG_FAN_SPEED " Obroty wiatraka:"
	#define MSG_FLOW " Przeplyw:"
	#define MSG_CONTROL " Kontrola \003"
	#define MSG_MIN " \002 Min:"
	#define MSG_MAX " \002 Max:"
	#define MSG_FACTOR " \002 Mnoznik:"
	#define MSG_AUTOTEMP " Auto. temp.:"
	#define MSG_ON "Wl. "
	#define MSG_OFF "Wyl."
	#define MSG_PID_P " PID-P: "
	#define MSG_PID_I " PID-I: "
	#define MSG_PID_D " PID-D: "
	#define MSG_PID_C " PID-C: "
	#define MSG_ACC  " Acc:"
	#define MSG_VXY_JERK " Zryw Vxy: "
	#define MSG_VMAX " Vmax "
	#define MSG_X "x:"
	#define MSG_Y "y:"
	#define MSG_Z "z:"
	#define MSG_E "e:"
	#define MSG_VMIN " Vmin:"
	#define MSG_VTRAV_MIN " Vskok min:"
	#define MSG_AMAX " Amax "
	#define MSG_A_RETRACT " A-wycofanie:"
	#define MSG_XSTEPS " krokiX/mm:"
	#define MSG_YSTEPS " krokiY/mm:"
	#define MSG_ZSTEPS " krokiZ/mm:"
	#define MSG_ESTEPS " krokiE/mm:"
	#define MSG_MAIN_WIDE " Menu        \003"
	#define MSG_RECTRACT_WIDE " Wycofanie   \x7E"
	#define MSG_TEMPERATURE_WIDE " Temperatura \x7E"
	#define MSG_TEMPERATURE_RTN " Temperatura  \003"
	#define MSG_MOTION_WIDE " Ruch        \x7E"
	#define MSG_STORE_EPROM " Zapisz w pamieci"
	#define MSG_LOAD_EPROM " Wczytaj z pamieci"
	#define MSG_RESTORE_FAILSAFE " Ustawienia fabryczne"
	#define MSG_REFRESH "\004Odswiez"
	#define MSG_WATCH " Obserwuj   \003"
	#define MSG_PREPARE " Przygotuj \x7E"
	#define MSG_PREPARE_ALT " Przygotuj \003"
	#define MSG_CONTROL_ARROW " Kontroluj \x7E"
	#define MSG_RETRACT_ARROW " Wycofaj \x7E"
	#define MSG_TUNE "Strojenie\x7E"
	#define MSG_PAUSE_PRINT "    Pauza    \x7E"
	#define MSG_RESUME_PRINT "  Wznowienie  \x7E"
	#define MSG_STOP_PRINT "     Stop     \x7E"
	#define MSG_CARD_MENU " Menu SDCard  \x7E"
	#define MSG_NO_CARD " Brak karty"
	#define MSG_DWELL "Uspij..."
	#define MSG_USERWAIT "Czekaj na uzytkownika..."
	#define MSG_NO_MOVE "Brak ruchu."
	#define MSG_PART_RELEASE "Czesciowe zwolnienie"
	#define MSG_KILLED "Ubity. "
	#define MSG_STOPPED "Zatrzymany. "
	#define MSG_STEPPER_RELEASED "Zwolniony."
	#define MSG_CONTROL_RETRACT  " Wycofaj mm:"
	#define MSG_CONTROL_RETRACTF " Wycofaj  F:"
	#define MSG_CONTROL_RETRACT_ZLIFT " Skok Z mm:"
	#define MSG_CONTROL_RETRACT_RECOVER " Cof. wycof. +mm:"
	#define MSG_CONTROL_RETRACT_RECOVERF " Cof. wycof.  F:"
	#define MSG_AUTORETRACT " Auto. wycofanie:"
        #define MSG_SERIAL_ERROR_MENU_STRUCTURE "Cos jest nie tak ze struktura menu."

// Serial Console Messages

	#define MSG_Enqueing "Kolejkowanie \""
	#define MSG_POWERUP "Zasilanie wlaczone"
	#define MSG_EXTERNAL_RESET " Reset (zewnetrzny)"
	#define MSG_BROWNOUT_RESET " Reset (spadek napiecia)"
	#define MSG_WATCHDOG_RESET " Reset (watchdog)"
	#define MSG_SOFTWARE_RESET " Reset (programowy)"
	#define MSG_MARLIN "Marlin "
	#define MSG_AUTHOR " | Autor: "
	#define MSG_CONFIGURATION_VER " Ostatnia aktualizacja: "
	#define MSG_FREE_MEMORY " Wolna pamiec: "
	#define MSG_PLANNER_BUFFER_BYTES "  Bufor planisty krokow (w bajtach): "
	#define MSG_OK "ok"
	#define MSG_FILE_SAVED "Plik zapisany."
	#define MSG_ERR_LINE_NO "Numer linijki nie jest ostatnim numerem linijki+1; ostatnia linijka:"
	#define MSG_ERR_CHECKSUM_MISMATCH "Niezgodna suma kontrolna; ostatnia linijka: "
	#define MSG_ERR_NO_CHECKSUM "Brak sumy kontrolnej w linijce; ostatnia linijka:"
	#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "Brak numery linijki przy sumie kontrolnej; ostatnia linijka:"
	#define MSG_FILE_PRINTED "Ukonczono wydruk z pliku"
	#define MSG_BEGIN_FILE_LIST "Start listy plikow"
	#define MSG_END_FILE_LIST "Koniec listy plikow"
	#define MSG_M104_INVALID_EXTRUDER "M104 Niepoprawny ekstruder "
	#define MSG_M105_INVALID_EXTRUDER "M105 Niepoprawny ekstruder "
	#define MSG_ERR_NO_THERMISTORS "Brak termistorow - brak temperatury :("
	#define MSG_M109_INVALID_EXTRUDER "M109 Niepoprawny ekstruder "
	#define MSG_HEATING "Nagrzewanie ekstrudera..."
	#define MSG_HEATING_COMPLETE "Nagrzewanie ekstrudera zakonczone."
	#define MSG_BED_HEATING "Nagrzewanie loza..."
	#define MSG_BED_DONE "Nagrzewanie loza zakonczone."
	#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
	#define MSG_COUNT_X " Liczenie X: "
	#define MSG_ERR_KILLED "Drukarka zatrzymana. Wywolano kill()"
	#define MSG_ERR_STOPPED "Drukarka zatrzymana z powodu bledu. Usun problem i zrestartuj drukartke komenda M999. (temperatura zostala zresetowana; ustaw temperature po restarcie)"
	#define MSG_RESEND "Wyslij ponownie: "
	#define MSG_UNKNOWN_COMMAND "Nieznane polecenie: \""
	#define MSG_ACTIVE_EXTRUDER "Aktywny ekstruder: "
	#define MSG_INVALID_EXTRUDER "Niepoprawny ekstruder"
	#define MSG_X_MIN "x_min: "
	#define MSG_X_MAX "x_max: "
	#define MSG_Y_MIN "y_min: "
	#define MSG_Y_MAX "y_max: "
	#define MSG_Z_MIN "z_min: "
	#define MSG_Z_MAX "z_max: "
	#define MSG_M119_REPORT "Zgloszenie statusu wylacznikow krancowych"
	#define MSG_ENDSTOP_HIT "WYZWOLONY"
	#define MSG_ENDSTOP_OPEN "otwarty"

	#define MSG_SD_CANT_OPEN_SUBDIR "Nie mozna otworzyc podkatalogu"
	#define MSG_SD_INIT_FAIL "Blad inicjalizacji karty SD"
	#define MSG_SD_VOL_INIT_FAIL "Blad inizjalizacji wolumenu"
	#define MSG_SD_OPENROOT_FAIL "Blad odczytywania katalogu glownego"
	#define MSG_SD_CARD_OK "Karta SD zainicjalizowana"
	#define MSG_SD_WORKDIR_FAIL "Blad odczytywania katalogu roboczego"
	#define MSG_SD_OPEN_FILE_FAIL "Nie mozna otworzyc pliku: "
	#define MSG_SD_FILE_OPENED "Otwarto plik:"
	#define MSG_SD_SIZE " Rozmiar:"
	#define MSG_SD_FILE_SELECTED "Wybrano plik"
	#define MSG_SD_WRITE_TO_FILE "Zapisywanie do pliku: "
	#define MSG_SD_PRINTING_BYTE "Drukowanie z karty SD, bajt "
	#define MSG_SD_NOT_PRINTING "Nie trwa drukowanie z karty SD"
	#define MSG_SD_ERR_WRITE_TO_FILE "blad podczas zapisu do pliku"
	#define MSG_SD_CANT_ENTER_SUBDIR "Nie mozna odczytac podkatalogu: "

	#define MSG_STEPPER_TO_HIGH "Za duza czestotliwosc krokow: "
	#define MSG_ENDSTOPS_HIT "Wylacznik krancowy zostal wyzwolony na pozycji: "
	#define MSG_ERR_COLD_EXTRUDE_STOP " uniemozliwiono zimna ekstruzje"
	#define MSG_ERR_LONG_EXTRUDE_STOP " uniemozliwiono zbyt dluga ekstruzje"

#endif


#if LANGUAGE_CHOICE == 3

#define WELCOME_MSG MACHINE_NAME " Pret."
#define MSG_SD_INSERTED "Carte inseree"
#define MSG_SD_REMOVED "Carte retiree"
#define MSG_MAIN " Principal \003"
#define MSG_AUTOSTART " Demarrage auto."
#define MSG_DISABLE_STEPPERS " Desactiver moteurs"
#define MSG_AUTO_HOME " Home auto."
#define MSG_SET_ORIGIN " Regler origine"
#define MSG_PREHEAT_PLA " Prechauffage PLA"
#define MSG_PREHEAT_PLA_SETTINGS " Regl. prechauffe PLA"
#define MSG_PREHEAT_ABS " Prechauffage ABS"
#define MSG_PREHEAT_ABS_SETTINGS " Regl. prechauffe ABS"
#define MSG_COOLDOWN " Refroidissement"
#define MSG_EXTRUDE " Extrusion"
#define MSG_RETRACT " Retractation"
#define MSG_PREHEAT_PLA " Prechauffage PLA"
#define MSG_PREHEAT_ABS " Prechauffage ABS"
#define MSG_MOVE_AXIS " Deplacer axe \x7E"
#define MSG_SPEED " Vitesse:"
#define MSG_NOZZLE " \002Buse:"
#define MSG_NOZZLE1 " \002Buse2:"
#define MSG_NOZZLE2 " \002Buse3:"
#define MSG_BED " \002Lit:"
#define MSG_FAN_SPEED " Vitesse ventilateur:"
#define MSG_FLOW " Flux:"
#define MSG_CONTROL " Controle \003"
#define MSG_MIN " \002 Min:"
#define MSG_MAX " \002 Max:"
#define MSG_FACTOR " \002 Facteur:"
#define MSG_AUTOTEMP " Temp. Auto.:"
#define MSG_ON "Marche "
#define MSG_OFF "Arret"
#define MSG_PID_P " PID-P: "
#define MSG_PID_I " PID-I: "
#define MSG_PID_D " PID-D: "
#define MSG_PID_C " PID-C: "
#define MSG_ACC " Acc:"
#define MSG_VXY_JERK " Vxy-jerk: "
#define MSG_VMAX " Vmax "
#define MSG_X "x:"
#define MSG_Y "y:"
#define MSG_Z "z:"
#define MSG_E "e:"
#define MSG_VMIN " Vmin:"
#define MSG_VTRAV_MIN " Vdepl min:"
#define MSG_AMAX " Amax "
#define MSG_A_RETRACT " A-retract:"
#define MSG_XSTEPS " Xpas/mm:"
#define MSG_YSTEPS " Ypas/mm:"
#define MSG_ZSTEPS " Zpas/mm:"
#define MSG_ESTEPS " Epas/mm:"
#define MSG_MAIN_WIDE " Principal \003"
#define MSG_RECTRACT_WIDE " Rectractater \x7E"
#define MSG_TEMPERATURE_WIDE " Temperature \x7E"
#define MSG_TEMPERATURE_RTN " Temperature \003"
#define MSG_MOTION_WIDE " Mouvement \x7E"
#define MSG_STORE_EPROM " Sauvegarder memoire"
#define MSG_LOAD_EPROM " Lire memoire"
#define MSG_RESTORE_FAILSAFE " Restaurer memoire"
#define MSG_REFRESH "\004Actualiser"
#define MSG_WATCH " Surveiller \003"
#define MSG_PREPARE " Preparer \x7E"
#define MSG_PREPARE_ALT " Prepare \003"
#define MSG_CONTROL_ARROW " Controle \x7E"
#define MSG_RETRACT_ARROW " Retracter \x7E"
#define MSG_TUNE " Regler \x7E"
#define MSG_PAUSE_PRINT " Pause impression \x7E"
#define MSG_RESUME_PRINT " Reprendre impression \x7E"
#define MSG_STOP_PRINT " Arreter impression \x7E"
#define MSG_CARD_MENU " Menu carte \x7E"
#define MSG_NO_CARD " Pas de carte"
#define MSG_DWELL "Repos..."
#define MSG_USERWAIT "Attente de l'utilisateur..."
#define MSG_NO_MOVE "Aucun mouvement."
#define MSG_PART_RELEASE "Relache partielle"
#define MSG_KILLED "TUE."
#define MSG_STOPPED "STOPPE."
#define MSG_STEPPER_RELEASED "RELACHE."
#define MSG_CONTROL_RETRACT " Retractation mm:"
#define MSG_CONTROL_RETRACTF " Retractation F:"
#define MSG_CONTROL_RETRACT_ZLIFT " Hop mm:"
#define MSG_CONTROL_RETRACT_RECOVER " UnRet +mm:"
#define MSG_CONTROL_RETRACT_RECOVERF " UnRet F:"
#define MSG_AUTORETRACT " Retract. Auto.:"
        #define MSG_SERIAL_ERROR_MENU_STRUCTURE "Erreur avec MenuStructure."

// Serial Console Messages

#define MSG_Enqueing "Mise en tampon \""
#define MSG_POWERUP "Allumage"
#define MSG_EXTERNAL_RESET " RAZ Externe"
#define MSG_BROWNOUT_RESET " RAZ defaut alim."
#define MSG_WATCHDOG_RESET " RAZ Watchdog"
#define MSG_SOFTWARE_RESET " RAZ logicielle"
#define MSG_MARLIN "Marlin "
#define MSG_AUTHOR " | Auteur: "
#define MSG_CONFIGURATION_VER " Derniere MaJ: "
#define MSG_FREE_MEMORY " Memoire libre: "
#define MSG_PLANNER_BUFFER_BYTES " PlannerBufferBytes: "
#define MSG_OK "ok"
#define MSG_FILE_SAVED "Fichier enregistre."
#define MSG_ERR_LINE_NO "Le numero de ligne n'est pas la derniere ligne + 1, derniere ligne: "
#define MSG_ERR_CHECKSUM_MISMATCH "Erreur somme de controle, derniere ligne: "
#define MSG_ERR_NO_CHECKSUM "Pas de somme de controle avec le numero de ligne, derniere ligne: "
#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "Pas de numero de ligne avec somme de controle, derniere ligne: "
#define MSG_FILE_PRINTED "Impression terminee"
#define MSG_BEGIN_FILE_LIST "Debut de la liste de fichiers"
#define MSG_END_FILE_LIST "Fin de la liste de fichiers"
#define MSG_M104_INVALID_EXTRUDER "M104 Extruder invalide"
#define MSG_M105_INVALID_EXTRUDER "M105 Extruder invalide"
#define MSG_ERR_NO_THERMISTORS "Pas de thermistor, pas de temperature"
#define MSG_M109_INVALID_EXTRUDER "M109 Extruder invalide "
#define MSG_HEATING "En chauffe..."
#define MSG_HEATING_COMPLETE "Chauffe terminee."
#define MSG_BED_HEATING "Chauffe du lit."
#define MSG_BED_DONE "Chauffe du lit terminee."
#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
#define MSG_COUNT_X " Compteur X: "
#define MSG_ERR_KILLED "Impression arretee. kill() appelee!"
#define MSG_ERR_STOPPED "Impression arretee a cause d'erreurs. Corriger les erreurs et utiliser M999 pour la reprendre. (Temperature remise a zero. Reactivez la apres redemarrage)"
#define MSG_RESEND "Renvoie: "
#define MSG_UNKNOWN_COMMAND "Commande inconnue: \""
#define MSG_ACTIVE_EXTRUDER "Extrudeur actif: "
#define MSG_INVALID_EXTRUDER "Extrudeur invalide"
#define MSG_X_MIN "x_min: "
#define MSG_X_MAX "x_max: "
#define MSG_Y_MIN "y_min: "
#define MSG_Y_MAX "y_max: "
#define MSG_Z_MIN "z_min: "
#define MSG_Z_MAX "z_max: "
#define MSG_M119_REPORT "Affichage du status des fin de course"
#define MSG_ENDSTOP_HIT "DECLENCHE"
#define MSG_ENDSTOP_OPEN "OUVERT"

#define MSG_SD_CANT_OPEN_SUBDIR "Impossible d'ouvrir le sous-repertoire"
#define MSG_SD_INIT_FAIL "Echec de l'initialisation de la SD"
#define MSG_SD_VOL_INIT_FAIL "Echec de volume.init"
#define MSG_SD_OPENROOT_FAIL "Echec openRoot"
#define MSG_SD_CARD_OK "Carte SD Ok"
#define MSG_SD_WORKDIR_FAIL "Echec d'ouverture workDir"
#define MSG_SD_OPEN_FILE_FAIL "Echec d'ouverture, Fichier: "
#define MSG_SD_FILE_OPENED "Fichier ouvert: "
#define MSG_SD_SIZE " Taille: "
#define MSG_SD_FILE_SELECTED "Fichier selectionne"
#define MSG_SD_WRITE_TO_FILE "Ecriture dans le fichier: "
#define MSG_SD_PRINTING_BYTE "Octet impression SD "
#define MSG_SD_NOT_PRINTING "Pas d'impression SD"
#define MSG_SD_ERR_WRITE_TO_FILE "Erreur d'ecriture dans le fichier"
#define MSG_SD_CANT_ENTER_SUBDIR "Impossible d'entrer dans le sous-repertoire: "

#define MSG_STEPPER_TO_HIGH "Steprate trop eleve: "
#define MSG_ENDSTOPS_HIT "Fin de course atteint: "
#define MSG_ERR_COLD_EXTRUDE_STOP " Extrusion a froid evitee"
#define MSG_ERR_LONG_EXTRUDE_STOP " Extrusion longue evitee"
	
#endif


#if LANGUAGE_CHOICE == 4

// LCD Menu Messages

	#define WELCOME_MSG MACHINE_NAME " Bereit."

	#define MSG_SD_INSERTED      "SDKarte erkannt"
	#define MSG_SD_REMOVED       "SDKarte entfernt"
	#define MSG_MAIN             " Hauptmne眉 \003"
	#define MSG_AUTOSTART        " Autostart"
	#define MSG_DISABLE_STEPPERS " Stepper abschalten"
	#define MSG_AUTO_HOME        " Auto Nullpunkt"
	#define MSG_SET_ORIGIN       " Setze Nullpunkt"
	#define MSG_PREHEAT_PLA      " Vorw盲rmen PLA"
	#define MSG_PREHEAT_PLA_SETTINGS " Vorw盲rmen PLA Einstellungen"
	#define MSG_PREHEAT_ABS      " Vorw盲rmen ABS"
	#define MSG_PREHEAT_ABS_SETTINGS "  Vorw盲rmen ABS Einstellungen"
	#define MSG_COOLDOWN         " Abk眉hlen"
	#define MSG_EXTRUDE          " Extrude"
	#define MSG_RETRACT          " Retract"
	#define MSG_MOVE_AXIS        " Achsen bewegen\x7E"
	#define MSG_SPEED            " Geschw:"
	#define MSG_NOZZLE           " \002D眉se:"
	#define MSG_NOZZLE1          " \002D眉se2:"
	#define MSG_NOZZLE2          " \002D眉se3:"
	#define MSG_BED              " \002Bett:"
	#define MSG_FAN_SPEED        " L眉ftergeschw.:"
	#define MSG_FLOW             " Flu脽:"
	#define MSG_CONTROL          " Einstellungen \003"
	#define MSG_MIN              " \002 Min:"
	#define MSG_MAX              " \002 Max:"
	#define MSG_FACTOR           " \002 Faktor:"
	#define MSG_AUTOTEMP         " AutoTemp:"
	#define MSG_ON               "Ein "
	#define MSG_OFF              "Aus "
	#define MSG_PID_P            " PID-P: "
	#define MSG_PID_I            " PID-I: "
	#define MSG_PID_D            " PID-D: "
	#define MSG_PID_C            " PID-C: "
	#define MSG_ACC              " Acc:"
	#define MSG_VXY_JERK         " Vxy-jerk: "
	#define MSG_VMAX             " Vmax "
	#define MSG_X                "x:"
	#define MSG_Y                "y:"
	#define MSG_Z                "z:"
	#define MSG_E                "e:"
	#define MSG_VMIN             " Vmin:"
	#define MSG_VTRAV_MIN        " VTrav min:"
	#define MSG_AMAX             " Amax "
	#define MSG_A_RETRACT        " A-Retract:"
	#define MSG_XSTEPS           " Xsteps/mm:"
	#define MSG_YSTEPS           " Ysteps/mm:"
	#define MSG_ZSTEPS           " Zsteps/mm:"
	#define MSG_ESTEPS           " Esteps/mm:"
	#define MSG_MAIN_WIDE        " Hauptmen眉     \003"
	#define MSG_RECTRACT_WIDE    " Rectract      \x7E"
	#define MSG_WATCH            " Beobachten    \003"
	#define MSG_TEMPERATURE_WIDE " Temperatur    \x7E"
        #define MSG_TEMPERATURE_RTN  " Temperatur    \003"
	#define MSG_MOTION_WIDE      " Bewegung      \x7E"
	#define MSG_STORE_EPROM      " EPROM speichern"
	#define MSG_LOAD_EPROM       " EPROM laden"
	#define MSG_RESTORE_FAILSAFE " Standardkonfig."
	#define MSG_REFRESH          "\004Aktualisieren"
	#define MSG_PREPARE          " Vorbereitung  \x7E"
	#define MSG_PREPARE_ALT      " Vorbereitung  \003"
	#define MSG_CONTROL_ARROW    " Einstellungen \x7E"
	#define MSG_TUNE             " Justierung    \x7E"
	#define MSG_PAUSE_PRINT      " Druck anhalten\x7E"
	#define MSG_RESUME_PRINT     " Druck fortsetz\x7E"
	#define MSG_STOP_PRINT       " Druck stoppen \x7E"
	#define MSG_CARD_MENU        " SDKarten Men眉 \x7E"
	#define MSG_NO_CARD          " Keine SDKarte"
	#define MSG_DWELL            "Warten..."		
	#define MSG_USERWAIT         "Warte auf Nutzer..."
	#define MSG_NO_MOVE          "Kein Zug."
	#define MSG_PART_RELEASE     "Stepper tlw frei"
	#define MSG_KILLED           "KILLED"
	#define MSG_STOPPED          "GESTOPPT"
	#define MSG_STEPPER_RELEASED "Stepper frei"
        #define MSG_CONTROL_RETRACT  " Retract mm:"
        #define MSG_CONTROL_RETRACTF " Retract  F:"
        #define MSG_CONTROL_RETRACT_ZLIFT " Hop mm:"
        #define MSG_CONTROL_RETRACT_RECOVER " UnRet +mm:"
        #define MSG_CONTROL_RETRACT_RECOVERF " UnRet  F:"
        #define MSG_AUTORETRACT      " AutoRetr.:"
	#define MSG_SERIAL_ERROR_MENU_STRUCTURE "Fehler in Men眉struktur."
	
// Serial Console Messages

	#define MSG_Enqueing "enqueing \""
	#define MSG_POWERUP "PowerUp"
	#define MSG_EXTERNAL_RESET " External Reset"
	#define MSG_BROWNOUT_RESET " Brown out Reset"
	#define MSG_WATCHDOG_RESET " Watchdog Reset"
	#define MSG_SOFTWARE_RESET " Software Reset"
	#define MSG_MARLIN "Marlin: "
	#define MSG_AUTHOR " | Author: "
	#define MSG_CONFIGURATION_VER " Last Updated: "
	#define MSG_FREE_MEMORY " Free Memory: "
	#define MSG_PLANNER_BUFFER_BYTES "  PlannerBufferBytes: "
	#define MSG_OK "ok"
	#define MSG_FILE_SAVED "Done saving file."
	#define MSG_ERR_LINE_NO "Line Number is not Last Line Number+1, Last Line:"
	#define MSG_ERR_CHECKSUM_MISMATCH "checksum mismatch, Last Line:"
	#define MSG_ERR_NO_CHECKSUM "No Checksum with line number, Last Line:"
	#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "No Line Number with checksum, Last Line:"
	#define MSG_FILE_PRINTED "Done printing file"
	#define MSG_BEGIN_FILE_LIST "Begin file list"
	#define MSG_END_FILE_LIST "End file list"
	#define MSG_M104_INVALID_EXTRUDER "M104 Invalid extruder "
	#define MSG_M105_INVALID_EXTRUDER "M105 Invalid extruder "
	#define MSG_ERR_NO_THERMISTORS "No thermistors - no temp"
	#define MSG_M109_INVALID_EXTRUDER "M109 Invalid extruder "
	#define MSG_HEATING "Heating..."
	#define MSG_HEATING_COMPLETE "Heating done."
	#define MSG_BED_HEATING "Bed Heating."
	#define MSG_BED_DONE "Bed done."
	#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
	#define MSG_COUNT_X " Count X:"
	#define MSG_ERR_KILLED "Printer halted. kill() called !!"
	#define MSG_ERR_STOPPED "Printer stopped due to errors. Fix the error and use M999 to restart!"
	#define MSG_RESEND "Resend:"
	#define MSG_UNKNOWN_COMMAND "Unknown command:\""
	#define MSG_ACTIVE_EXTRUDER "Active Extruder: "
	#define MSG_INVALID_EXTRUDER "Invalid extruder"
	#define MSG_X_MIN "x_min: "
	#define MSG_X_MAX "x_max: "
	#define MSG_Y_MIN "y_min: "
	#define MSG_Y_MAX "y_max: "
	#define MSG_Z_MIN "z_min: "
	#define MSG_Z_MAX "z_max: "
	#define MSG_M119_REPORT "Reporting endstop status"
	#define MSG_ENDSTOP_HIT "TRIGGERED"
	#define MSG_ENDSTOP_OPEN "open"

	#define MSG_SD_CANT_OPEN_SUBDIR "Cannot open subdir"
	#define MSG_SD_INIT_FAIL "SD init fail"
	#define MSG_SD_VOL_INIT_FAIL "volume.init failed"
	#define MSG_SD_OPENROOT_FAIL "openRoot failed"
	#define MSG_SD_CARD_OK "SD card ok"
	#define MSG_SD_WORKDIR_FAIL "workDir open failed"
	#define MSG_SD_OPEN_FILE_FAIL "open failed, File: "
	#define MSG_SD_FILE_OPENED "File opened:"
	#define MSG_SD_SIZE " Size:"
	#define MSG_SD_FILE_SELECTED "File selected"
	#define MSG_SD_WRITE_TO_FILE "Writing to file: "
	#define MSG_SD_PRINTING_BYTE "SD printing byte "
	#define MSG_SD_NOT_PRINTING "Not SD printing"
	#define MSG_SD_ERR_WRITE_TO_FILE "error writing to file"
	#define MSG_SD_CANT_ENTER_SUBDIR "Cannot enter subdir:"

	#define MSG_STEPPER_TO_HIGH "Steprate to high : "
	#define MSG_ENDSTOPS_HIT "endstops hit: "
	#define MSG_ERR_COLD_EXTRUDE_STOP " cold extrusion prevented"
	#define MSG_ERR_LONG_EXTRUDE_STOP " too long extrusion prevented"

#endif


#if LANGUAGE_CHOICE == 5

// LCD Menu Messages
#define WELCOME_MSG MACHINE_NAME " Lista."
#define MSG_SD_INSERTED "Tarjeta SD Colocada"
#define MSG_SD_REMOVED "Tarjeta SD Retirada"
#define MSG_MAIN " Menu Principal \003"
#define MSG_AUTOSTART " Autostart"
#define MSG_DISABLE_STEPPERS " Apagar Motores"
#define MSG_AUTO_HOME " Llevar Ejes al Cero"
#define MSG_SET_ORIGIN " Establecer Cero"
#define MSG_COOLDOWN " Enfriar"
#define MSG_EXTRUDE " Extruir"
#define MSG_RETRACT " Retraer"
#define MSG_PREHEAT_PLA " Precalentar PLA"
#define MSG_PREHEAT_PLA_SETTINGS " Ajustar temp. PLA"
#define MSG_PREHEAT_ABS " Precalentar ABS"
#define MSG_PREHEAT_ABS_SETTINGS " Ajustar temp. ABS"
#define MSG_MOVE_AXIS " Mover Ejes      \x7E"
#define MSG_SPEED " Velocidad:"
#define MSG_NOZZLE " \002Nozzle:"
#define MSG_NOZZLE1 " \002Nozzle2:"
#define MSG_NOZZLE2 " \002Nozzle3:"
#define MSG_BED " \002Base:"
#define MSG_FAN_SPEED " Ventilador:"
#define MSG_FLOW " Flujo:"
#define MSG_CONTROL " Control \003"
#define MSG_MIN " \002 Min:"
#define MSG_MAX " \002 Max:"
#define MSG_FACTOR " \002 Fact:"
#define MSG_AUTOTEMP " Autotemp:"
#define MSG_ON "On "
#define MSG_OFF "Off"
#define MSG_PID_P " PID-P: "
#define MSG_PID_I " PID-I: "
#define MSG_PID_D " PID-D: "
#define MSG_PID_C " PID-C: "
#define MSG_ACC  " Acc:"
#define MSG_VXY_JERK " Vxy-jerk: "
#define MSG_VMAX " Vmax "
#define MSG_X "x:"
#define MSG_Y "y:"
#define MSG_Z "z:"
#define MSG_E "e:"
#define MSG_VMIN " Vmin:"
#define MSG_VTRAV_MIN " VTrav min:"
#define MSG_AMAX " Amax "
#define MSG_A_RETRACT " A-retrac.:"
#define MSG_XSTEPS " Xpasos/mm:"
#define MSG_YSTEPS " Ypasos/mm:"
#define MSG_ZSTEPS " Zpasos/mm:"
#define MSG_ESTEPS " Epasos/mm:"
#define MSG_MAIN_WIDE " Menu Principal  \003"
#define MSG_RECTRACT_WIDE " Retraer         \x7E"
#define MSG_TEMPERATURE_WIDE " Temperatura     \x7E"
#define MSG_TEMPERATURE_RTN  " Temperatura     \003"
#define MSG_MOTION_WIDE " Movimiento      \x7E"
#define MSG_STORE_EPROM " Guardar Memoria"
#define MSG_LOAD_EPROM " Cargar Memoria"
#define MSG_RESTORE_FAILSAFE " Rest. de emergencia"
#define MSG_REFRESH "\004Volver a cargar"
#define MSG_WATCH " Monitorizar \003"
#define MSG_PREPARE " Preparar \x7E"
#define MSG_PREPARE_ALT " Preparar \003"
#define MSG_CONTROL_ARROW " Control  \x7E"
#define MSG_RETRACT_ARROW " Retraer  \x7E"
#define MSG_TUNE " Ajustar \x7E"
#define MSG_PAUSE_PRINT " Pausar Impresion \x7E"
#define MSG_RESUME_PRINT " Reanudar Impresion \x7E"
#define MSG_STOP_PRINT " Detener Impresion \x7E"
#define MSG_CARD_MENU " Menu de SD    \x7E"
#define MSG_NO_CARD " No hay Tarjeta SD"
#define MSG_DWELL "Reposo..."
#define MSG_USERWAIT "Esperando Ordenes..."
#define MSG_NO_MOVE "Sin movimiento"
#define MSG_PART_RELEASE "Desacople Parcial"
#define MSG_KILLED "PARADA DE EMERGENCIA. "
#define MSG_STOPPED "PARADA. "
#define MSG_STEPPER_RELEASED "Desacoplada."
#define MSG_CONTROL_RETRACT  " Retraer mm:"
#define MSG_CONTROL_RETRACTF " Retraer  F:"
#define MSG_CONTROL_RETRACT_ZLIFT " Levantar mm:"
#define MSG_CONTROL_RETRACT_RECOVER " DesRet +mm:"
#define MSG_CONTROL_RETRACT_RECOVERF " DesRet F:"
#define MSG_AUTORETRACT " AutoRetr.:"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE "Hay un error en la estructura del menu"

// Serial Console Messages

#define MSG_Enqueing "En cola \""
#define MSG_POWERUP "PowerUp"
#define MSG_EXTERNAL_RESET " Reset Externo"
#define MSG_BROWNOUT_RESET " Reset por Voltaje Incorrecto"
#define MSG_WATCHDOG_RESET " Reset por Bloqueo"
#define MSG_SOFTWARE_RESET " Reset por Software"
#define MSG_MARLIN "Marlin "
#define MSG_AUTHOR " | Autor: "
#define MSG_CONFIGURATION_VER " Ultima actualizacion: "
#define MSG_FREE_MEMORY " Memoria libre: "
#define MSG_PLANNER_BUFFER_BYTES "  PlannerBufferBytes: "
#define MSG_OK "ok"
#define MSG_FILE_SAVED "Guardado."
#define MSG_ERR_LINE_NO "El Numero de Linea no es igual al Ultimo Numero de Linea+1, Ultima Linea:"
#define MSG_ERR_CHECKSUM_MISMATCH "el checksum no coincide, Ultima Linea:"
#define MSG_ERR_NO_CHECKSUM "No se pudo hallar el Checksum con el numero de linea, Ultima Linea:"
#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "No se hallo el Numero de Linea con el Checksum, Ultima Linea:"
#define MSG_FILE_PRINTED "Impresion terminada"
#define MSG_BEGIN_FILE_LIST "Comienzo de la lista de archivos"
#define MSG_END_FILE_LIST "Fin de la lista de archivos"
#define MSG_M104_INVALID_EXTRUDER "M104 Extrusor Invalido "
#define MSG_M105_INVALID_EXTRUDER "M105 Extrusor Invalido "
#define MSG_ERR_NO_THERMISTORS "No hay termistores - no temp"
#define MSG_M109_INVALID_EXTRUDER "M109 Extrusor Invalido "
#define MSG_HEATING "Calentando..."
#define MSG_HEATING_COMPLETE "Calentamiento Hecho."
#define MSG_BED_HEATING "Calentando la base."
#define MSG_BED_DONE "Base Caliente."
#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
#define MSG_COUNT_X " Cuenta X:"
#define MSG_ERR_KILLED "隆隆Impresora Parada con kill()!!"
#define MSG_ERR_STOPPED "隆Impresora parada por errores. Arregle el error y use M999 Para reiniciar!. (La temperatura se reestablece. Ajustela antes de continuar)"
#define MSG_RESEND "Reenviar:"
#define MSG_UNKNOWN_COMMAND "Comando Desconocido:\""
#define MSG_ACTIVE_EXTRUDER "Extrusor Activo: "
#define MSG_INVALID_EXTRUDER "Extrusor Invalido"
#define MSG_X_MIN "x_min: "
#define MSG_X_MAX "x_max: "
#define MSG_Y_MIN "y_min: "
#define MSG_Y_MAX "y_max: "
#define MSG_Z_MIN "z_min: "
#define MSG_M119_REPORT "Comprobando fines de carrera."
#define MSG_ENDSTOP_HIT "PULSADO"
#define MSG_ENDSTOP_OPEN "abierto"
        
#define MSG_SD_CANT_OPEN_SUBDIR "No se pudo abrir la subcarpeta."
#define MSG_SD_INIT_FAIL "Fallo al iniciar la SD"
#define MSG_SD_VOL_INIT_FAIL "Fallo al montar el volumen"
#define MSG_SD_OPENROOT_FAIL "Fallo al abrir la carpeta raiz"
#define MSG_SD_CARD_OK "Tarjeta SD OK"
#define MSG_SD_WORKDIR_FAIL "Fallo al abrir la carpeta de trabajo"
#define MSG_SD_OPEN_FILE_FAIL "Error al abrir, Archivo: "
#define MSG_SD_FILE_OPENED "Archivo abierto:"
#define MSG_SD_SIZE " Tama帽o:"
#define MSG_SD_FILE_SELECTED "Archivo Seleccionado"
#define MSG_SD_WRITE_TO_FILE "Escribiendo en el archivo: "
#define MSG_SD_PRINTING_BYTE "SD imprimiendo el byte "
#define MSG_SD_NOT_PRINTING "No se esta imprimiendo con SD"
#define MSG_SD_ERR_WRITE_TO_FILE "Error al escribir en el archivo"
#define MSG_SD_CANT_ENTER_SUBDIR "No se puede abrir la carpeta:"

#define MSG_STEPPER_TO_HIGH "Steprate demasiado alto : "
#define MSG_ENDSTOPS_HIT "Se ha tocado el fin de carril: "
#define MSG_ERR_COLD_EXTRUDE_STOP " extrusion fria evitada"
#define MSG_ERR_LONG_EXTRUDE_STOP " extrusion demasiado larga evitada"

#endif

#if LANGUAGE_CHOICE == 6

// LCD Menu Messages
#define WELCOME_MSG MACHINE_NAME			" 袚芯褌芯胁."
#define MSG_SD_INSERTED						"袣邪褉褌邪 胁褋褌邪胁谢械薪邪"
#define MSG_SD_REMOVED						"袣邪褉褌邪 懈蟹胁谢械褔械薪邪"
#define MSG_MAIN							" 袦械薪褞              \003"
#define MSG_AUTOSTART						" 袗胁褌芯褋褌邪褉褌          "
#define MSG_DISABLE_STEPPERS				" 袙褘泻谢褞褔懈褌褜 写胁懈谐邪褌械谢懈"
#define MSG_AUTO_HOME						" 袩邪褉泻芯胁泻邪           "
#define MSG_SET_ORIGIN						" 袟邪锌芯屑薪懈褌褜 薪芯谢褜     "
#define MSG_PREHEAT_PLA						" 袩褉械写薪邪谐褉械胁 PLA     "
#define MSG_PREHEAT_PLA_SETTINGS			" 袧邪褋褌褉. 锌褉械写薪邪谐褉.PLA"
#define MSG_PREHEAT_ABS						" 袩褉械写薪邪谐褉械胁 ABS     "
#define MSG_PREHEAT_ABS_SETTINGS			" 袧邪褋褌褉. 锌褉械写薪邪谐褉.ABS"
#define MSG_COOLDOWN						" 袨褏谢邪卸写械薪懈械         "
#define MSG_EXTRUDE							" 协泻褋褌褉褍蟹懈褟          "
#define MSG_RETRACT							" 袨褌泻邪褌"
#define MSG_MOVE_AXIS						" 袛胁懈卸械薪懈械 锌芯 芯褋褟屑  \x7E"
#define MSG_SPEED							" 小泻芯褉芯褋褌褜:"
#define MSG_NOZZLE							" \002 肖懈谢褜械褉邪:"
#define MSG_NOZZLE1							" \002 肖懈谢褜械褉邪2:"
#define MSG_NOZZLE2							" \002 肖懈谢褜械褉邪3:"
#define MSG_BED								" \002 袣褉芯胁邪褌褜:"
#define MSG_FAN_SPEED						" 袣褍谢谢械褉:"
#define MSG_FLOW							" 袩芯褌芯泻:"
#define MSG_CONTROL							" 袧邪褋褌褉芯泄泻懈 \003"
#define MSG_MIN								" \002 袦懈薪懈屑褍屑:"
#define MSG_MAX								" \002 袦邪泻褋懈屑褍屑:"
#define MSG_FACTOR							" \002 肖邪泻褌芯褉:"
#define MSG_AUTOTEMP						" Autotemp:"
#define MSG_ON								"袙泻谢. "
#define MSG_OFF								"袙褘泻谢. "
#define MSG_PID_P							" PID-P: "
#define MSG_PID_I							" PID-I: "
#define MSG_PID_D							" PID-D: "
#define MSG_PID_C							" PID-C: "
#define MSG_ACC								" Acc:"
#define MSG_VXY_JERK						" Vxy-jerk: "
#define MSG_VMAX							" Vmax "
#define MSG_X								"x:"
#define MSG_Y								"y:"
#define MSG_Z								"z:"
#define MSG_E								"e:"
#define MSG_VMIN							" Vmin:"
#define MSG_VTRAV_MIN						" VTrav min:"
#define MSG_AMAX							" Amax "
#define MSG_A_RETRACT						" A-retract:"
#define MSG_XSTEPS							" X 褕邪谐/mm:"
#define MSG_YSTEPS							" Y 褕邪谐/mm:"
#define MSG_ZSTEPS							" Z 褕邪谐/mm:"
#define MSG_ESTEPS							" E 褕邪谐/mm:"
#define MSG_MAIN_WIDE						" 袦械薪褞              \003"
#define MSG_RECTRACT_WIDE					" 袨褌泻邪褌 锌芯写邪褔懈      \x7E"
#define MSG_TEMPERATURE_WIDE				" 孝械屑锌械褉邪褌褍褉邪       \x7E"
#define MSG_TEMPERATURE_RTN					" 孝械屑锌械褉邪褌褍褉邪       \003"
#define MSG_MOTION_WIDE						" 小泻芯褉芯褋褌懈          \x7E"
#define MSG_STORE_EPROM						" 小芯褏褉邪薪懈褌褜 薪邪褋褌褉芯泄泻懈"
#define MSG_LOAD_EPROM						" 袟邪谐褉褍蟹懈褌褜 薪邪褋褌褉芯泄泻懈"
#define MSG_RESTORE_FAILSAFE				" 小斜褉芯褋 薪邪褋褌褉芯械泻     "
#define MSG_REFRESH							"\004袨斜薪芯胁懈褌褜           "
#define MSG_WATCH							" 袨斜蟹芯褉             \003"
#define MSG_PREPARE							" 袛械泄褋褌胁懈褟          \x7E"
#define MSG_PREPARE_ALT						" 袛械泄褋褌胁懈褟          \003"
#define MSG_CONTROL_ARROW					" 袧邪褋褌褉芯泄泻懈         \x7E"
#define MSG_RETRACT_ARROW					" 袧邪褋褌褉芯泄泻懈 芯褌泻邪褌邪  \x7E"
#define MSG_TUNE							" Tune              \x7E"
#define MSG_PAUSE_PRINT						" 袩邪褍蟹邪 锌械褔邪褌懈      \x7E"
#define MSG_RESUME_PRINT					" 袩褉芯写芯谢卸懈褌褜 锌械褔邪褌褜 \x7E"
#define MSG_STOP_PRINT						" 袨褋褌邪薪芯胁懈褌褜 锌械褔邪褌褜 \x7E"
#define MSG_CARD_MENU						" 袦械薪褞 泻邪褉褌褘        \x7E"
#define MSG_NO_CARD							" 袧械褌 泻邪褉褌褘"
#define MSG_DWELL							"小芯薪..."
#define MSG_USERWAIT						"袧邪卸屑懈褌械 写谢褟 锌褉芯写芯谢卸."
#define MSG_NO_MOVE							"袧械褌 写胁懈卸械薪懈褟.       "
#define MSG_PART_RELEASE					" 袠蟹胁谢械褔械薪懈械 锌褉懈薪褌邪  "
#define MSG_KILLED							"校袘袠孝袨. "
#define MSG_STOPPED							"袨小孝袗袧袨袙袥袝袧袨. "
#define MSG_STEPPER_RELEASED				"袛胁懈谐邪褌械谢懈 芯褌泻谢褞褔械薪褘."
#define MSG_CONTROL_RETRACT					" 袨褌泻邪褌 mm:"
#define MSG_CONTROL_RETRACTF				" 袨褌泻邪褌  F:"
#define MSG_CONTROL_RETRACT_ZLIFT			" 袩褉褘卸芯泻 mm:"
#define MSG_CONTROL_RETRACT_RECOVER			" 袙芯蟹胁褉邪褌 +mm:"
#define MSG_CONTROL_RETRACT_RECOVERF		" 袙芯蟹胁褉邪褌  F:"
#define MSG_AUTORETRACT						" 袗胁褌芯袨褌泻邪褌:"
#define MSG_SERIAL_ERROR_MENU_STRUCTURE		"袨褕懈斜泻邪 胁 褋褌褉褍泻褌褍褉械 屑械薪褞."

// Serial Console Messages

#define MSG_Enqueing						"袟邪锌谢邪薪懈褉芯胁邪薪芯 \""
#define MSG_POWERUP							"袙泻谢褞褔械薪懈械 锌懈褌邪薪懈褟"
#define MSG_EXTERNAL_RESET					" 袙薪械褕薪懈泄 褋斜褉芯褋"
#define MSG_BROWNOUT_RESET					" Brown out 褋斜褉芯褋"
#define MSG_WATCHDOG_RESET					" Watchdog 褋斜褉芯褋"
#define MSG_SOFTWARE_RESET					" 锌褉芯谐褉邪屑屑薪褘泄 褋斜褉芯褋"
#define MSG_MARLIN							"Marlin "
#define MSG_AUTHOR							" | 袗胁褌芯褉: "
#define MSG_CONFIGURATION_VER				" 袩芯褋谢械写薪械械 芯斜薪芯胁谢械薪懈械: "
#define MSG_FREE_MEMORY						" 袩邪屑褟褌懈 褋胁芯斜芯写薪芯: "
#define MSG_PLANNER_BUFFER_BYTES			"  袘褍褎褎械褉 芯褔械褉械写懈 泻芯屑邪薪写 Bytes: "
#define MSG_OK								"ok"
#define MSG_FILE_SAVED						"肖邪泄谢 蟹邪锌懈褋邪薪."
#define MSG_ERR_LINE_NO						"袧芯屑械薪 褋褌褉芯泻懈 褝褌芯 薪械 锌芯褋谢械写薪褟褟 褋褌褉芯泻邪+1, 锌芯褋谢械写薪褟褟 褋褌褉芯泻邪:"
#define MSG_ERR_CHECKSUM_MISMATCH			"泻芯薪褌褉芯谢褜薪邪褟 褋褍屑屑邪 薪械 褋芯胁锌邪写邪械褌, 锌芯褋谢械写薪褟褟 褋褌褉芯泻邪:"
#define MSG_ERR_NO_CHECKSUM					"薪械褌 泻芯薪褌褉芯谢褜薪芯泄 褋褍屑屑褘 写谢褟 褋褌褉芯泻懈, 锌芯褋谢械写薪褟褟 褋褌褉芯泻邪:"
#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM	"薪械褌 褋褌褉芯泻懈 写谢褟 泻芯薪褌褉芯谢褜薪芯泄 褋褍屑屑褘, 锌芯褋谢械写薪褟褟 褋褌褉芯泻邪:"
#define MSG_FILE_PRINTED					"袩械褔邪褌褜 褎邪泄谢邪 蟹邪胁械褉褕械薪邪"
#define MSG_BEGIN_FILE_LIST					"小锌懈褋芯泻 褎邪泄谢芯胁"
#define MSG_END_FILE_LIST					"袣芯薪械褑 褋锌懈褋泻邪 褎邪泄谢芯胁"
#define MSG_M104_INVALID_EXTRUDER			"M104 芯褕懈斜泻邪 褝泻褋褌褉褍写械褉邪 "
#define MSG_M105_INVALID_EXTRUDER			"M105 芯褕懈斜泻邪 褝泻褋褌褉褍写械褉邪 "
#define MSG_ERR_NO_THERMISTORS				"袧械褌 褌械褉屑懈褋褌褉邪 - 薪械褌 褌械屑锌械褉邪褌褍褉褘"
#define MSG_M109_INVALID_EXTRUDER			"M109 芯褕懈斜泻邪 褝泻褋褌褉褍写械褉邪 "
#define MSG_HEATING							"袧邪谐褉械胁...  "
#define MSG_HEATING_COMPLETE				"袧邪褉谐械褌芯.    "
#define MSG_BED_HEATING						"袧邪谐褉械胁 褋褌芯谢邪...     "
#define MSG_BED_DONE						"小褌芯谢 薪邪谐褉械褌.        "
#define MSG_M115_REPORT						"FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
#define MSG_COUNT_X							" Count X:"
#define MSG_ERR_KILLED						"袩褉懈薪褌械褉 芯褋褌邪薪芯胁谢械薪. 胁褘蟹芯胁 kill() !!"
#define MSG_ERR_STOPPED						"袨褕懈斜泻邪 锌褉懈薪褌械褉邪, 芯褋褌邪薪芯胁. 校褋褌褉邪薪懈褌械 薪械懈褋锌褉邪胁薪芯褋褌褜 懈 懈褋锌芯谢褜蟹褍泄褌械 M999 写谢褟 锌械褉械蟹邪谐褉褍蟹泻懈!. (孝械屑锌械褉邪褌褍褉邪 薪械写芯褋褌褍锌薪邪. 袩褉芯胁械褉褜褌械 写邪褌褔懈泻懈)"
#define MSG_RESEND							"袩械褉械芯褌锌褉邪胁泻邪:"
#define MSG_UNKNOWN_COMMAND					"袧械懈蟹胁械褋褌薪邪褟 泻芯屑邪薪写邪:\""
#define MSG_ACTIVE_EXTRUDER					"袗泻褌懈胁薪褘泄 褝泻褋褌褉褍写械褉: "
#define MSG_INVALID_EXTRUDER				"袨褕懈斜泻邪 褝泻褋褌褉褍写械褉邪"
#define MSG_X_MIN							"x_min:"
#define MSG_X_MAX							"x_max:"
#define MSG_Y_MIN							"y_min:"
#define MSG_Y_MAX							"y_max:"
#define MSG_Z_MIN							"z_min:"
#define MSG_Z_MAX							"z_max:"

#define MSG_SD_CANT_OPEN_SUBDIR				"袧械 芯褌泻褉褘褌褜 锌邪锌泻褍"
#define MSG_SD_INIT_FAIL					"袨褕懈斜泻邪 懈薪懈褑懈邪谢懈蟹邪褑懈懈 SD"
#define MSG_SD_VOL_INIT_FAIL				"袨褕懈斜泻邪 懈薪懈褑懈邪谢懈蟹邪褑懈懈 褉邪蟹写械谢邪"
#define MSG_SD_OPENROOT_FAIL				"袧械 锌褉芯褔械褋褌褜 褋芯写械褉卸懈屑芯械 泻芯褉薪褟"
#define MSG_SD_CARD_OK						"SD 泻邪褉褌邪 胁 锌芯褉褟写泻械"
#define MSG_SD_WORKDIR_FAIL					"薪械 芯褌泻褉褘褌褜 褉邪斜芯褔褍褞 锌邪锌泻褍"
#define MSG_SD_OPEN_FILE_FAIL				"袨褕懈斜泻邪 褔褌械薪懈褟, 褎邪泄谢: "
#define MSG_SD_FILE_OPENED					"肖邪泄谢 芯褌泻褉褘褌:"
#define MSG_SD_SIZE							" 袪邪蟹屑械褉:"
#define MSG_SD_FILE_SELECTED				"肖邪泄谢 胁褘斜褉邪薪"
#define MSG_SD_WRITE_TO_FILE				"袟邪锌懈褋褜 胁 褎邪泄谢: "
#define MSG_SD_PRINTING_BYTE				"SD 锌械褔邪褌褜 byte "
#define MSG_SD_NOT_PRINTING					"薪械褌 SD 锌械褔邪褌懈"
#define MSG_SD_ERR_WRITE_TO_FILE			"芯褕懈斜泻邪 蟹邪锌懈褋懈 胁 褎邪泄谢"
#define MSG_SD_CANT_ENTER_SUBDIR			"袧械 蟹邪泄褌懈 胁 锌邪锌泻褍:"

#define MSG_STEPPER_TO_HIGH					"效邪褋褌芯褌邪 褕邪谐芯胁 芯褔械薪褜 胁褘褋芯泻邪 : "
#define MSG_ENDSTOPS_HIT					"泻芯薪褑械胁懈泻 褋褉邪斜芯褌邪谢: "
#define MSG_ERR_COLD_EXTRUDE_STOP			" 蟹邪褖懈褌邪 褏芯谢芯写薪芯泄 褝泻褋褌褉褍蟹懈懈"
#define MSG_ERR_LONG_EXTRUDE_STOP			" 蟹邪褖懈褌邪 锌褉械胁褘褕械薪懈褟 写谢懈薪薪褘 褝泻褋褌褉褍蟹懈懈"
#define MSG_M119_REPORT						"小褌邪褌褍褋 泻芯薪褑械胁懈泻芯胁"
#define MSG_ENDSTOP_HIT						"小褉邪斜邪褌褘胁邪薪懈械 泻芯薪褑械胁懈泻邪"
#define MSG_ENDSTOP_OPEN					"袣芯薪褑械胁懈泻 芯褋胁芯斜芯卸写械薪"

#endif


#if LANGUAGE_CHOICE == 7

	// LCD Menu Messages
	#define WELCOME_MSG MACHINE_NAME " Pronto."
	#define MSG_SD_INSERTED          "SD Card inserita"
	#define MSG_SD_REMOVED           "SD Card rimossa"
	#define MSG_MAIN                 " Menu principale \003"
	#define MSG_AUTOSTART            " Autostart"
	#define MSG_DISABLE_STEPPERS     " Disabilita Motori Passo-Passo"
	#define MSG_AUTO_HOME            " Auto Home"
	#define MSG_SET_ORIGIN           " Imposta Origini Assi"
	#define MSG_PREHEAT_PLA          " Preriscalda PLA"
	#define MSG_PREHEAT_PLA_SETTINGS " Impostazioni Preriscaldamento PLA"
	#define MSG_PREHEAT_ABS          " Preriscalda ABS"
	#define MSG_PREHEAT_ABS_SETTINGS " Impostazioni Preriscaldamento ABS"
	#define MSG_COOLDOWN             " Rafredda"
	#define MSG_EXTRUDE              " Estrudi"
	#define MSG_RETRACT              " Ritrai"
	#define MSG_MOVE_AXIS            " Muovi Asse      \x7E"
	#define MSG_SPEED                " Velcit脿:"
	#define MSG_NOZZLE               " \002Ugello:"
	#define MSG_NOZZLE1              " \002Ugello2:"
	#define MSG_NOZZLE2              " \002Ugello3:"
	#define MSG_BED                  " \002Piatto:"
	#define MSG_FAN_SPEED            " Velocit脿 Ventola:"
	#define MSG_FLOW                 " Flusso:"
	#define MSG_CONTROL              " Controllo \003"
	#define MSG_MIN                  " \002 Min:"
	#define MSG_MAX                  " \002 Max:"
	#define MSG_FACTOR               " \002 Fact:"
	#define MSG_AUTOTEMP             " Autotemp:"
	#define MSG_ON                   "On "
	#define MSG_OFF                  "Off"
	#define MSG_PID_P                " PID-P: "
	#define MSG_PID_I                " PID-I: "
	#define MSG_PID_D                " PID-D: "
	#define MSG_PID_C                " PID-C: "
	#define MSG_ACC                  " Acc:"
	#define MSG_VXY_JERK             " Vxy-jerk: "
	#define MSG_VMAX                 " Vmax "
	#define MSG_X                    "x:"
	#define MSG_Y                    "y:"
	#define MSG_Z                    "z:"
	#define MSG_E                    "e:"
	#define MSG_VMIN                 " Vmin:"
	#define MSG_VTRAV_MIN            " VTrav min:"
	#define MSG_AMAX                 " Amax "
	#define MSG_A_RETRACT            " A-ritrai:"
	#define MSG_XSTEPS               " Xpassi/mm:"
	#define MSG_YSTEPS               " Ypassi/mm:"
	#define MSG_ZSTEPS               " Zpassi/mm:"
	#define MSG_ESTEPS               " Epassi/mm:"
	#define MSG_MAIN_WIDE            " Menu Principale        \003"
	#define MSG_RECTRACT_WIDE        " Ritrai    \x7E"
	#define MSG_TEMPERATURE_WIDE     " Temperatura \x7E"
	#define MSG_TEMPERATURE_RTN      " Temperatura  \003"
	#define MSG_MOTION_WIDE          " Movimento      \x7E"
	#define MSG_STORE_EPROM          " Salva in memoria"
	#define MSG_LOAD_EPROM           " Carica dalla memoria"
	#define MSG_RESTORE_FAILSAFE     " Configurazioni di default"
	#define MSG_REFRESH              "\004Aggiorna"
	#define MSG_WATCH                " Guarda   \003"
	#define MSG_PREPARE              " Prepara \x7E"
	#define MSG_PREPARE_ALT          " Prepara \003"
	#define MSG_CONTROL_ARROW        " Controllo \x7E"
	#define MSG_RETRACT_ARROW        " Ritrai \x7E"
	#define MSG_TUNE                 " Tune    \x7E"
	#define MSG_PAUSE_PRINT          " Metti in Pausa la Stampa \x7E"
	#define MSG_RESUME_PRINT         " Riprendi Stampa \x7E"
	#define MSG_STOP_PRINT           " Arresta Stampa   \x7E"
	#define MSG_CARD_MENU            " Card Menu    \x7E"
	#define MSG_NO_CARD              " No Card"
	#define MSG_DWELL                " Sospensione..."
	#define MSG_USERWAIT             "Attendi utente..."
	#define MSG_NO_MOVE              "Nessun movimento."
	#define MSG_PART_RELEASE         "Rilascio Parziale"
	#define MSG_KILLED               "UCCISO. "
	#define MSG_STOPPED              "ARRESTATO. "
	#define MSG_STEPPER_RELEASED     "Rilasciato."
	#define MSG_CONTROL_RETRACT      " Ritrai mm:"
	#define MSG_CONTROL_RETRACTF     " Ritrai  F:"
	#define MSG_CONTROL_RETRACT_ZLIFT " Salta mm:"
	#define MSG_CONTROL_RETRACT_RECOVER " UnRet +mm:"
	#define MSG_CONTROL_RETRACT_RECOVERF " UnRet  F:"
	#define MSG_AUTORETRACT          " AutoRilascio.:"
	#define MSG_SERIAL_ERROR_MENU_STRUCTURE "Qualcosa non va in MenuStructure."

	// Serial Console Messages

	#define MSG_Enqueing             "accodamento \""
	#define MSG_POWERUP              "Accensione"
	#define MSG_EXTERNAL_RESET       " Reset Esterno"
	#define MSG_BROWNOUT_RESET       " Brown out Reset"
	#define MSG_WATCHDOG_RESET       " Watchdog Reset"
	#define MSG_SOFTWARE_RESET       " Software Reset"
	#define MSG_MARLIN               "Marlin "
	#define MSG_AUTHOR               " | Autore: "
	#define MSG_CONFIGURATION_VER    " Ultimo Aggiornamento: "
	#define MSG_FREE_MEMORY          " Memoria Libera: "
	#define MSG_PLANNER_BUFFER_BYTES "  PlannerBufferBytes: "
	#define MSG_OK                   "ok"
	#define MSG_FILE_SAVED           "File Salvato."
	#define MSG_ERR_LINE_NO          "Il Numero della Linea non corrisponde al Numero dell'Ultima Linea+1, Ultima Linea:"
	#define MSG_ERR_CHECKSUM_MISMATCH "checksum non corrispondente, Ultima Linea:"
	#define MSG_ERR_NO_CHECKSUM      "Nessun Checksum con Numero di Linea, Ultima Linea:"
	#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "Nessun Numero di Linea con Checksum, Ultima Linea:"
	#define MSG_FILE_PRINTED         "File stampato"
	#define MSG_BEGIN_FILE_LIST      "Inizio Lista File"
	#define MSG_END_FILE_LIST        "Fine Lista File"
	#define MSG_M104_INVALID_EXTRUDER "M104 Estrusore non valido "
	#define MSG_M105_INVALID_EXTRUDER "M105 Estrusore non valido "
	#define MSG_ERR_NO_THERMISTORS   "Nessun Termistore - nessuna temperatura"
	#define MSG_M109_INVALID_EXTRUDER "M109 Estrusore non valido "
	#define MSG_HEATING              "Riscaldamento..."
	#define MSG_HEATING_COMPLETE     "Riscaldamento concluso."
	#define MSG_BED_HEATING          "Riscaldamento Piatto."
	#define MSG_BED_DONE             "Piatto Pronto."
	#define MSG_M115_REPORT          "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
	#define MSG_COUNT_X              " Calcola X:"
	#define MSG_ERR_KILLED           "Stampante Calda. kill() chiamata !!"
	#define MSG_ERR_STOPPED          "Stampante fermata a causa di errori. Risolvi l'errore e usa M999 per ripartire!. (Reset temperatura. Impostala prima di ripartire)"
	#define MSG_RESEND               "Reinviato:"
	#define MSG_UNKNOWN_COMMAND      "Comando sconosciuto:\""
	#define MSG_ACTIVE_EXTRUDER      "Attiva Estrusore: "
	#define MSG_INVALID_EXTRUDER     "Estrusore non valido"
	#define MSG_X_MIN                "x_min: "
	#define MSG_X_MAX                "x_max: "
	#define MSG_Y_MIN                "y_min: "
	#define MSG_Y_MAX                "y_max: "
	#define MSG_Z_MIN                "z_min: "
	#define MSG_Z_MAX                "z_max: "
	#define MSG_M119_REPORT          "Segnalazione stato degli endstop"
	#define MSG_ENDSTOP_HIT          "INNESCATO"
	#define MSG_ENDSTOP_OPEN         "aperto"

	#define MSG_SD_CANT_OPEN_SUBDIR  "Impossibile aprire sottocartella"
	#define MSG_SD_INIT_FAIL         "Fallita Inizializzazione SD"
	#define MSG_SD_VOL_INIT_FAIL     "Fallito il montaggio del Volume"
	#define MSG_SD_OPENROOT_FAIL     "Fallita l'apertura Cartella Principale"
	#define MSG_SD_CARD_OK           "SD card ok"
	#define MSG_SD_WORKDIR_FAIL      "Fallita l'apertura Cartella di Lavoro"
	#define MSG_SD_OPEN_FILE_FAIL    "Fallita l'apertura del File: "
	#define MSG_SD_FILE_OPENED       "File aperto:"
	#define MSG_SD_SIZE              " Dimensione:"
	#define MSG_SD_FILE_SELECTED     "File selezionato"
	#define MSG_SD_WRITE_TO_FILE     "Scrittura su file: "
	#define MSG_SD_PRINTING_BYTE     "Si sta scrivendo il byte su SD "
	#define MSG_SD_NOT_PRINTING      "Non si sta scrivendo su SD"
	#define MSG_SD_ERR_WRITE_TO_FILE "Errore nella scrittura su file"
	#define MSG_SD_CANT_ENTER_SUBDIR "Impossibile entrare nella sottocartella:"

	#define MSG_STEPPER_TO_HIGH      "Steprate troppo alto : "
	#define MSG_ENDSTOPS_HIT         "Raggiunto il fondo carrello: "
	#define MSG_ERR_COLD_EXTRUDE_STOP " prevenuta estrusione fredda"
	#define MSG_ERR_LONG_EXTRUDE_STOP " prevenuta estrusione troppo lunga"

#endif


#if LANGUAGE_CHOICE == 8

// LCD Menu Messages
	#define WELCOME_MSG MACHINE_NAME " Pronta."
	#define MSG_SD_INSERTED "Cartao SD inserido"
	#define MSG_SD_REMOVED "Cartao SD removido"
	#define MSG_MAIN " Menu Principal \003"
	#define MSG_AUTOSTART " Autostart"
	#define MSG_DISABLE_STEPPERS " Apagar Motores"
	#define MSG_AUTO_HOME " Ir para Origen"
	#define MSG_SET_ORIGIN " Estabelecer Origen"
	#define MSG_PREHEAT_PLA " pre-aquecer PLA"
	#define MSG_PREHEAT_PLA_SETTINGS " pre-aquecer PLA Setting"
	#define MSG_PREHEAT_ABS " pre-aquecer ABS"
	#define MSG_PREHEAT_ABS_SETTINGS " pre-aquecer ABS Setting"
	#define MSG_COOLDOWN " Esfriar"
	#define MSG_EXTRUDE " Extrudar"
	#define MSG_RETRACT " Retrair"
	#define MSG_PREHEAT_PLA " pre-aquecer PLA"
	#define MSG_PREHEAT_ABS " pre-aquecer ABS"
	#define MSG_MOVE_AXIS " Mover eixo      \x7E"
	#define MSG_SPEED " Velocidade:"
	#define MSG_NOZZLE " \002Nozzle:"
	#define MSG_NOZZLE1 " \002Nozzle2:"
	#define MSG_NOZZLE2 " \002Nozzle3:"
	#define MSG_BED " \002Base:"
	#define MSG_FAN_SPEED " Velocidade Ventoinha:"
	#define MSG_FLOW " Fluxo:"
	#define MSG_CONTROL " Controle \003"
	#define MSG_MIN " \002 Min:"
	#define MSG_MAX " \002 Max:"
	#define MSG_FACTOR " \002 Fact:"
	#define MSG_AUTOTEMP " Autotemp:"
	#define MSG_ON "On "
	#define MSG_OFF "Off"
	#define MSG_PID_P " PID-P: "
	#define MSG_PID_I " PID-I: "
	#define MSG_PID_D " PID-D: "
	#define MSG_PID_C " PID-C: "
	#define MSG_ACC  " Acc:"
	#define MSG_VXY_JERK " Vxy-jerk: "
	#define MSG_VMAX " Vmax "
	#define MSG_X "x:"
	#define MSG_Y "y:"
	#define MSG_Z "z:"
	#define MSG_E "e:"
	#define MSG_VMIN " Vmin:"
	#define MSG_VTRAV_MIN " VTrav min:"
	#define MSG_AMAX " Amax "
	#define MSG_A_RETRACT " A-retract:"
	#define MSG_XSTEPS " Xpasso/mm:"
	#define MSG_YSTEPS " Ypasso/mm:"
	#define MSG_ZSTEPS " Zpasso/mm:"
	#define MSG_ESTEPS " Epasso/mm:"
	#define MSG_MAIN_WIDE " Menu Principal  \003"
	#define MSG_RECTRACT_WIDE " Retrair    \x7E"
	#define MSG_TEMPERATURE_WIDE " Temperatura \x7E"
	#define MSG_TEMPERATURE_RTN " Temperatura  \003"
	#define MSG_MOTION_WIDE " Movimento     \x7E"
	#define MSG_STORE_EPROM " Guardar memoria"
	#define MSG_LOAD_EPROM " Carregar memoria"
	#define MSG_RESTORE_FAILSAFE " Rest. de emergencia"
	#define MSG_REFRESH "\004Recarregar"
	#define MSG_WATCH " Monitorar   \003"
	#define MSG_PREPARE " Preparar \x7E"
	#define MSG_PREPARE_ALT " Preparar \003"
	#define MSG_CONTROL_ARROW " Controle \x7E"
	#define MSG_RETRACT_ARROW " Retrair \x7E"
	#define MSG_TUNE " Tune    \x7E"
	#define MSG_PAUSE_PRINT " Pausar Impressao \x7E"
	#define MSG_RESUME_PRINT " Resumir Impressao \x7E"
	#define MSG_STOP_PRINT " Parar Impressao   \x7E"
	#define MSG_CARD_MENU " Menu cartao SD    \x7E"
	#define MSG_NO_CARD " Sem cartao SD"
	#define MSG_DWELL "Repouso..."
	#define MSG_USERWAIT "Esperando Ordem..."
	#define MSG_NO_MOVE "Sem movimento."
	#define MSG_PART_RELEASE "Lancamento Parcial"
	#define MSG_KILLED "PARADA DE EMERGENCIA. "
	#define MSG_STOPPED "PARADA. "
	#define MSG_STEPPER_RELEASED "Lancado."
	#define MSG_CONTROL_RETRACT  " Retrair mm:"
	#define MSG_CONTROL_RETRACTF " Retrair  F:"
	#define MSG_CONTROL_RETRACT_ZLIFT " Levantar mm:"
	#define MSG_CONTROL_RETRACT_RECOVER " DesRet +mm:"
	#define MSG_CONTROL_RETRACT_RECOVERF " DesRet  F:"
	#define MSG_AUTORETRACT " AutoRetr.:"
        #define MSG_SERIAL_ERROR_MENU_STRUCTURE "Algo esta errado na estrutura do Menu."

// Serial Console Messages

	#define MSG_Enqueing "enqueing \""
	#define MSG_POWERUP "PowerUp"
	#define MSG_EXTERNAL_RESET " Reset Externo"
	#define MSG_BROWNOUT_RESET " Reset por voltagem incorreta"
	#define MSG_WATCHDOG_RESET " Reset por Bloqueio"
	#define MSG_SOFTWARE_RESET " Reset por Software"
	#define MSG_MARLIN "Marlin "
	#define MSG_AUTHOR " | Author: "
	#define MSG_CONFIGURATION_VER " Ultima atualizacao: "
	#define MSG_FREE_MEMORY " memoria Livre: "
	#define MSG_PLANNER_BUFFER_BYTES "  PlannerBufferBytes: "
	#define MSG_OK "ok"
	#define MSG_FILE_SAVED "Guardado."
	#define MSG_ERR_LINE_NO "O Numero da linha Nao e igual ao ultimo Numero da linha+1, Ultima linha:"
	#define MSG_ERR_CHECKSUM_MISMATCH "O checksum Nao coincide, Ultima linha:"
	#define MSG_ERR_NO_CHECKSUM "Nao foi possivel encontrar o checksum com o numero da linha, Ultima linha :"
	#define MSG_ERR_NO_LINENUMBER_WITH_CHECKSUM "Nao ha o numero da linha com o checksum, Ultima linha:"
	#define MSG_FILE_PRINTED "Impressao terminada"
	#define MSG_BEGIN_FILE_LIST "Come莽o da lista de arquivos"
	#define MSG_END_FILE_LIST "Fim da lista de arquivos"
	#define MSG_M104_INVALID_EXTRUDER "M104 Extrusor inv谩lido "
	#define MSG_M105_INVALID_EXTRUDER "M105 Extrusor inv谩lido "
	#define MSG_ERR_NO_THERMISTORS "Nao ha termistor - no temp"
	#define MSG_M109_INVALID_EXTRUDER "M109 Extrusor inv谩lido "
	#define MSG_HEATING "Aquecendo..."
	#define MSG_HEATING_COMPLETE "Aquecido."
	#define MSG_BED_HEATING "Aquecendo a Base."
	#define MSG_BED_DONE "Base quente."
	#define MSG_M115_REPORT "FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:" FIRMWARE_URL " PROTOCOL_VERSION:" PROTOCOL_VERSION " MACHINE_TYPE:" MACHINE_NAME " EXTRUDER_COUNT:" STRINGIFY(EXTRUDERS) "\n"
	#define MSG_COUNT_X " Conta X:"
	#define MSG_ERR_KILLED "Impressora parada com kill() !!"
	#define MSG_ERR_STOPPED "Impressora parada por erros. Coserte o erro e use M999 para recome莽ar!. (Temperatura reiniciada. Ajuste antes de recome莽ar)"
	#define MSG_RESEND "Reenviar:"
	#define MSG_UNKNOWN_COMMAND "Comando desconhecido:\""
	#define MSG_ACTIVE_EXTRUDER "Extrusor ativo: "
	#define MSG_INVALID_EXTRUDER "Extrusor invalido"
	#define MSG_X_MIN "x_min: "
	#define MSG_X_MAX "x_max: "
	#define MSG_Y_MIN "y_min: "
	#define MSG_Y_MAX "y_max: "
	#define MSG_Z_MIN "z_min: "
	#define MSG_Z_MAX "z_max: "
	#define MSG_M119_REPORT "Relatando estado do ponto final"
	#define MSG_ENDSTOP_HIT "PULSADO"
	#define MSG_ENDSTOP_OPEN "Aberto"

	#define MSG_SD_CANT_OPEN_SUBDIR "Nao pode abrir sub diretorio"
	#define MSG_SD_INIT_FAIL "Falha ao iniciar SD"
	#define MSG_SD_VOL_INIT_FAIL "Falha ao montar volume"
	#define MSG_SD_OPENROOT_FAIL "Falha ao abrir diretorio raiz"
	#define MSG_SD_CARD_OK "cartao SD ok"
	#define MSG_SD_WORKDIR_FAIL "Falha ao abrir diretorio de trabalho"
	#define MSG_SD_OPEN_FILE_FAIL "Erro ao abrir, Arquivo: "
	#define MSG_SD_FILE_OPENED "Arquivo aberto:"
	#define MSG_SD_SIZE " Size:"
	#define MSG_SD_FILE_SELECTED "Arquivo selecionado"
	#define MSG_SD_WRITE_TO_FILE "Escrevendo no arquivo: "
	#define MSG_SD_PRINTING_BYTE "SD imprimindo o byte "
	#define MSG_SD_NOT_PRINTING "Nao esta se imprimindo com o SD"
	#define MSG_SD_ERR_WRITE_TO_FILE "Erro ao escrever no arquivo"
	#define MSG_SD_CANT_ENTER_SUBDIR "Nao pode abrir o sub diretorio:"

	#define MSG_STEPPER_TO_HIGH "Steprate muito alto : "
	#define MSG_ENDSTOPS_HIT "O ponto final foi tocado: "
	#define MSG_ERR_COLD_EXTRUDE_STOP " Extrusao a frio evitada"
	#define MSG_ERR_LONG_EXTRUDE_STOP " Extrusao muito larga evitada"


#endif

#endif // ifndef LANGUAGE_H

